name: Publish ZIP on merge to main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Zip and publish Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare tag and zip name
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          TIMESTAMP=$(date -u +"%Y%m%dT%H%M%SZ")
          TAG="v${TIMESTAMP}-${SHORT_SHA}"
          # Fixed zip name requested by user
          ZIP_NAME="PactpiaResoucepack.zip"
          echo "TAG=${TAG}" >> $GITHUB_OUTPUT
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_OUTPUT

      - name: Create ZIP archive
        run: |
          ZIP_NAME=${{ steps.vars.outputs.ZIP_NAME }}
          # Exclude Git internals and workflow files
          zip -r "$ZIP_NAME" . -x ".git/*" ".github/*" "node_modules/*" "**/__pycache__/*" || true
          ls -lh "$ZIP_NAME"

      - name: Create Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.TAG }}
          name: ${{ steps.vars.outputs.TAG }}
          files: ${{ steps.vars.outputs.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
